const Types = {
  SET_COUNTER: 'SET_COUNTER',
  FETCH_POSTS: {
    REQUEST: 'FETCH_POSTS_REQUEST', 
    SUCCESS: 'FETCH_POSTS_SUCCESS', 
    FAILURE: 'FETCH_POSTS_FAILURE', 
  },
  FETCH_POST: {
    REQUEST: 'FETCH_POST_REQUEST', 
    SUCCESS: 'FETCH_POST_SUCCESS', 
    FAILURE: 'FETCH_POST_FAILURE', 
  }
}

export default Types;